server:
    port: 8090

spring:
    jersey:
        type: filter

broker:
    partitions: 10
    topic: "karma-sample"
    session-timeout: 30000
    consumer:
        group-id: test
        enable-auto-commit: true
        auto-commit-interval: 1000
    producer:
        batch-size: 16384
        buffer-size: 33554432

