server:
    port: 8090

spring:
    jersey:
        type: filter

broker:
    partitions: 11
    topic: "karma-sample"
    session-timeout: 30000
    consumer:
        group-id: test
        enable-auto-commit: false
        auto-commit-interval: 1000
        enable-duplicates: true
        duplicates: 10
    producer:
        batch-size: 16384
        buffer-size: 33554432
