server:
    port: 8090

spring:
    jersey:
        type: filter
    profiles: default

broker:
    bootstrapServer: localhost:9092
    partitions: 10
    topic: "karma-sample"
    session-timeout: 30000
    consumer:
        group-id: test
        enable-auto-commit: true
        auto-commit-interval: 1000
    producer:
        batch-size: 16384
        linger-time-ms: 0
        buffer-size: 33554432

